### ISSUE TITLE
Links to other approaches

### ISSUE THREAD

**Issue by dill** [pedersen-fisheries-lab/DFO-3day-gam-workshop#3]
I've added a fair amount of material to section 6.

What is currently missing is:

- [x] `brms` (Gavin)
- [ ] `mgcViz`
- [x] `mgcvUtils`
- [x] `gratia` (Gavin)
- anything else

I don't know much about the above stuff (aside from `mgcvUtils`, obvs!). So if you are able to fill-in some blanks there that would be great. I am of course happy if you make changes to what is there, but please warn me so I can look through before I talk through the slides!

**Comment by gavinsimpson** [comment]
I can do something on *gratia* (but will wait to see what others have done/said elsewhere).

I'll also do something on *brms*

**Comment by eric-pedersen** [comment]
I'm going to include some `gratia` plots, as I think it is a great way of evaluating the model, but I won't dig into the details much.

**Comment by gavinsimpson** [comment]
I'm using *gratia* quite a bit in the predictions & variance part too. I will add a few slides on overview to section 6 this evening

**Comment by gavinsimpson** [comment]
Have added some stuff on *brms* and *gratia* now. I can tweak / add / remove stuff once I see what others have prepared for the various packages.
